# Site settings
baseurl: ""
url: "https://anitas.com.br/"

permalink: pretty

# paginação do blog
paginate: 5
paginate_path: "/blog/:num/"
excerpt_separator: <!--resumo-->

# Build settings
markdown: kramdown

kramdown:
  input: GFM

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

